grpc.v1:                                               // 
  - event.v1                                           // ✅ 
  - sandbox.controller.v1:                             // ✅
      - runtime.v2:                                    // ✅
          - event.v1                                   // ✅
          - metadata.v1:                               // ✅
              - content.v1                             // ✅
              - snapshotter.v1                         // ✅
      - sandbox.store.v1:                              // ✅
          - metadata.v1:                               // ✅
              - content.v1                             // ✅
              - snapshotter.v1                         // ✅
      - event.v1                                       // ✅
  - streaming.v1:                                      // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - snapshotter.v1                                     // ✅
  - nri.v1                                             // ✅
  - lease.v1:                                          // ✅
      - gc.v1:                                         // ✅
          - metadata.v1:                               // ✅
              - content.v1                             // ✅
              - snapshotter.v1                         // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - service.v1                                         // ✅
  - sandbox.store.v1:                                  // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - warning.v1                                         // ✅
  - transfer.v1:                                       // ✅
      - differ.v1:                                     // ✅
          - metadata.v1:                               // ✅
              - content.v1                             // ✅
              - snapshotter.v1                         // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
      - lease.v1:                                      // ✅
          - gc.v1:                                     // ✅
              - metadata.v1:                           // ✅
                  - content.v1                         // ✅
                  - snapshotter.v1                     // ✅
          - metadata.v1:                               // ✅
              - content.v1                             // ✅
              - snapshotter.v1                         // ✅
internal.v1:                                           // ✅
  - event.v1                                           // ✅
  - warning.v1                                         // ✅
  - tracing.processor.v1                               // ✅
  - service.v1                                         // ✅
service.v1:                                            // ✅
  - event.v1                                           // ✅
  - gc.v1:                                             // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - monitor.v1:                                        // ✅
      - event.v1                                       // ✅
  - differ.v1:                                         // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - runtime.v2:                                        // ✅
      - event.v1                                       // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - metadata.v1:                                       // ✅
      - content.v1                                     // ✅
      - snapshotter.v1                                 // ✅
  - runtime.v1:                                        // ✅
      - event.v1                                       // ✅
      - metadata.v1:                                   // ✅
          - content.v1                                 // ✅
          - snapshotter.v1                             // ✅
  - warning.v1                                         // ✅
